### ISSUE TITLE
64-bit for Catalina

### ISSUE THREAD

**Issue by t-bullock** [JanX2/AudioSlicer-macOS#1]
Any chance this will be updated to run on Catalina?

**Comment by JanX2** [comment]
I will have a look at how much effort this would entail.

**Comment by JanX2** [comment]
I updated the code to at least build and run on Catalina. There still are issues with actually playing audio. The audiothread seems to be aborted early for some reason.

**Comment by JanX2** [comment]
Seems like I have fixed all issue that got in the way of using the app. You should be able to build it with the current release of Xcode.
